# Generated by Django 5.2.15 on 2026-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='collect_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of {"key","description"} objects to extract from each call transcript.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='lead_followup_instructions',
            field=models.TextField(blank=True, help_text='Guidance for composing the follow-up email sent to the lead.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='notify_emails',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_lead_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_operator_summary',
            field=models.BooleanField(default=True),
        ),
    ]
