# Generated by Django 5.2.15 on 2026-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meeting_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
