# Generated by Django 5.2.15 on 2026-06-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('voicemail', 'Voicemail')], default='initiated', max_length=20)),
                ('disposition', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback', 'Callback'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='seconds')),
                ('recording_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.campaign')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=10)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='calls.call')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
