# Generated by Django 5.2.15 on 2026-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
    ]
